# Generated by Django 4.2.6 on 2023-12-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buaadb_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="ID",
            field=models.AutoField(
                db_column="project_id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="stuapplyteam",
            name="status",
            field=models.BooleanField(
                db_column="status", default=False, max_length=128
            ),
        ),
        migrations.CreateModel(
            name="TeamNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notice_id",
                    models.ForeignKey(
                        db_column="notice_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buaadb_backend.notice",
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        db_column="team_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buaadb_backend.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_notice",
            },
        ),
    ]
